---
- name: Import SSH public key to AWS
  amazon.aws.ec2_key:
    name: "{{ ssh_key_name }}"
# TODO - fix hard coding of key name and location
    key_material: "{{ lookup('file', '../vault/my_key.pub') }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Create EC2 instance
  amazon.aws.ec2_instance:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    region: "{{ aws_region }}"
    key_name: "{{ ssh_key_name }}"
    vpc_subnet_id: "{{ subnet_id }}"
    security_group: "{{ security_group }}"
    network:
      assign_public_ip: true
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: "{{ ebs_volume_size }}"
          delete_on_termination: true
    state: present
    wait: yes
  register: ec2_instance

# TODO: Getting an dict attribute error when referencing this module
#       https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_info_module.html
- name: Delay to allow for EC2 readiness
  ansible.builtin.pause:
    seconds: "{{ instance_delay_seconds }}"

- name: Display instance information
  debug:
    msg: 
      - "Instance created with ID {{ ec2_instance.instances[0].instance_id }}"
      - "Public IP: {{ ec2_instance.instances[0].public_ip_address }}"

- name: Set generated server_ip as a fact for other roles
  ansible.builtin.set_fact:
    server_ip: "{{ ec2_instance.instances[0].public_ip_address }}"


